# Generated by Django 3.2.4 on 2022-01-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Genere', models.CharField(choices=[('Man', 'Masculine'), ('Woman', 'Femenine'), ('Ind', 'Indistint')], default='', max_length=100)),
            ],
        ),
    ]
