# Generated by Django 3.2.4 on 2022-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20220112_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Salt',
            field=models.CharField(default='', max_length=300),
        ),
    ]
