# Generated by Django 3.2.4 on 2022-01-16 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20220115_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.employ'),
        ),
    ]
