# Generated by Django 3.2.4 on 2022-01-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_account_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Genere',
        ),
    ]
