# Generated by Django 3.2.4 on 2022-01-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_account_genere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Employees',
        ),
    ]
